import type { TimelineEvent, LabResult } from '@/lib/types';

// Mock timeline events used as fallback if DB is empty
export const mockTimelineEvents: Omit<TimelineEvent, 'id' | 'patient_id'>[] = [
  { event_type: 'visit', title: 'General OPD Visit', description: 'Routine checkup for hypertension', event_date: '2024-01-15', category: 'visit', severity: 'normal', metadata: { doctor: 'Dr. Sharma', diagnosis: 'Hypertension Stage 1' } },
  { event_type: 'lab', title: 'Complete Blood Count', description: 'Hemoglobin: 11.2 g/dL (low)', event_date: '2024-02-01', category: 'lab', severity: 'abnormal', metadata: { test: 'CBC', value: '11.2', unit: 'g/dL', range: '13-17' } },
  { event_type: 'prescription', title: 'Amlodipine 5mg', description: 'Once daily for BP control', event_date: '2024-02-01', category: 'prescription', severity: 'normal', metadata: { medication: 'Amlodipine', dose: '5mg', frequency: 'OD' } },
  { event_type: 'lab', title: 'Lipid Profile', description: 'Total cholesterol: 245 mg/dL (high)', event_date: '2024-03-10', category: 'lab', severity: 'abnormal', metadata: { test: 'Lipid Profile', value: '245', unit: 'mg/dL', range: '<200' } },
  { event_type: 'prescription', title: 'Atorvastatin 10mg', description: 'Once daily at bedtime', event_date: '2024-03-10', category: 'prescription', severity: 'normal', metadata: { medication: 'Atorvastatin', dose: '10mg', frequency: 'HS' } },
  { event_type: 'visit', title: 'Cardiology Consultation', description: 'Chest pain evaluation - ECG normal', event_date: '2024-04-20', category: 'visit', severity: 'normal', metadata: { doctor: 'Dr. Patel', diagnosis: 'Non-cardiac chest pain' } },
  { event_type: 'procedure', title: 'ECG', description: '12-lead ECG - normal sinus rhythm', event_date: '2024-04-20', category: 'procedure', severity: 'normal', metadata: { type: 'ECG', result: 'Normal sinus rhythm' } },
  { event_type: 'lab', title: 'HbA1c', description: '6.8% (borderline)', event_date: '2024-05-05', category: 'lab', severity: 'abnormal', metadata: { test: 'HbA1c', value: '6.8', unit: '%', range: '<5.7' } },
  { event_type: 'visit', title: 'Diabetes Screening', description: 'Pre-diabetic - lifestyle counseling', event_date: '2024-05-05', category: 'visit', severity: 'normal', metadata: { doctor: 'Dr. Gupta', diagnosis: 'Pre-diabetes' } },
  { event_type: 'prescription', title: 'Metformin 500mg', description: 'Twice daily with meals', event_date: '2024-05-05', category: 'prescription', severity: 'normal', metadata: { medication: 'Metformin', dose: '500mg', frequency: 'BD' } },
  { event_type: 'lab', title: 'Fasting Glucose', description: '126 mg/dL (borderline)', event_date: '2024-06-12', category: 'lab', severity: 'abnormal', metadata: { test: 'Fasting Glucose', value: '126', unit: 'mg/dL', range: '70-100' } },
  { event_type: 'document', title: 'Discharge Summary', description: 'Previous hospitalization for pneumonia', event_date: '2024-06-25', category: 'document', severity: 'normal', metadata: { source: 'City Hospital', type: 'Discharge summary' } },
  { event_type: 'lab', title: 'TSH', description: '3.2 mIU/L (normal)', event_date: '2024-07-15', category: 'lab', severity: 'normal', metadata: { test: 'TSH', value: '3.2', unit: 'mIU/L', range: '0.4-4.0' } },
  { event_type: 'visit', title: 'Quarterly Review', description: 'BP controlled, diabetes improving', event_date: '2024-08-01', category: 'visit', severity: 'normal', metadata: { doctor: 'Dr. Sharma', diagnosis: 'Stable' } },
  { event_type: 'lab', title: 'HbA1c Follow-up', description: '6.2% (improving)', event_date: '2024-09-05', category: 'lab', severity: 'abnormal', metadata: { test: 'HbA1c', value: '6.2', unit: '%', range: '<5.7' } },
  { event_type: 'prescription', title: 'Vitamin D3', description: 'Weekly for 8 weeks', event_date: '2024-09-05', category: 'prescription', severity: 'normal', metadata: { medication: 'Vitamin D3', dose: '60000 IU', frequency: 'Weekly' } },
  { event_type: 'procedure', title: 'Eye Examination', description: 'Fundus screening - no retinopathy', event_date: '2024-10-10', category: 'procedure', severity: 'normal', metadata: { type: 'Fundoscopy', result: 'No diabetic retinopathy' } },
  { event_type: 'lab', title: 'Kidney Function', description: 'Creatinine: 1.4 mg/dL (slightly high)', event_date: '2024-11-01', category: 'lab', severity: 'abnormal', metadata: { test: 'KFT', value: '1.4', unit: 'mg/dL', range: '0.6-1.2' } },
  { event_type: 'document', title: 'Lab Report Upload', description: 'Thyroid panel results', event_date: '2024-11-20', category: 'document', severity: 'normal', metadata: { source: 'Thyrocare', type: 'Lab report' } },
  { event_type: 'visit', title: 'Annual Checkup', description: 'Comprehensive health assessment', event_date: '2025-01-10', category: 'visit', severity: 'normal', metadata: { doctor: 'Dr. Sharma', diagnosis: 'Overall stable' } },
];

// Mock lab results for trend charts
export const mockLabResults: Omit<LabResult, 'id' | 'patient_id'>[] = [
  { test_name: 'HbA1c', value: 6.8, unit: '%', reference_range: '<5.7', flagged: true, category: 'Diabetes', test_date: '2024-05-05' },
  { test_name: 'HbA1c', value: 6.2, unit: '%', reference_range: '<5.7', flagged: true, category: 'Diabetes', test_date: '2024-09-05' },
  { test_name: 'HbA1c', value: 5.9, unit: '%', reference_range: '<5.7', flagged: true, category: 'Diabetes', test_date: '2025-01-10' },
  { test_name: 'Fasting Glucose', value: 126, unit: 'mg/dL', reference_range: '70-100', flagged: true, category: 'Diabetes', test_date: '2024-06-12' },
  { test_name: 'Fasting Glucose', value: 118, unit: 'mg/dL', reference_range: '70-100', flagged: true, category: 'Diabetes', test_date: '2024-09-05' },
  { test_name: 'Fasting Glucose', value: 105, unit: 'mg/dL', reference_range: '70-100', flagged: true, category: 'Diabetes', test_date: '2025-01-10' },
  { test_name: 'Total Cholesterol', value: 245, unit: 'mg/dL', reference_range: '<200', flagged: true, category: 'Lipids', test_date: '2024-03-10' },
  { test_name: 'Total Cholesterol', value: 210, unit: 'mg/dL', reference_range: '<200', flagged: true, category: 'Lipids', test_date: '2024-08-01' },
  { test_name: 'Total Cholesterol', value: 195, unit: 'mg/dL', reference_range: '<200', flagged: false, category: 'Lipids', test_date: '2025-01-10' },
  { test_name: 'Creatinine', value: 1.4, unit: 'mg/dL', reference_range: '0.6-1.2', flagged: true, category: 'Renal', test_date: '2024-11-01' },
  { test_name: 'Creatinine', value: 1.3, unit: 'mg/dL', reference_range: '0.6-1.2', flagged: true, category: 'Renal', test_date: '2025-01-10' },
  { test_name: 'Hemoglobin', value: 11.2, unit: 'g/dL', reference_range: '13-17', flagged: true, category: 'CBC', test_date: '2024-02-01' },
  { test_name: 'Hemoglobin', value: 12.5, unit: 'g/dL', reference_range: '13-17', flagged: true, category: 'CBC', test_date: '2024-08-01' },
  { test_name: 'Hemoglobin', value: 13.1, unit: 'g/dL', reference_range: '13-17', flagged: false, category: 'CBC', test_date: '2025-01-10' },
  { test_name: 'TSH', value: 3.2, unit: 'mIU/L', reference_range: '0.4-4.0', flagged: false, category: 'Thyroid', test_date: '2024-07-15' },
  { test_name: 'TSH', value: 2.8, unit: 'mIU/L', reference_range: '0.4-4.0', flagged: false, category: 'Thyroid', test_date: '2024-11-20' },
];

// Red flag keywords for detection
export const redFlagRules: { keywords: string[]; severity: 'high' | 'critical' | 'medium'; label: string }[] = [
  { keywords: ['severe chest pain', 'chest pain', 'crushing chest'], severity: 'critical', label: 'Severe chest pain' },
  { keywords: ['shortness of breath', 'breathing difficulty', 'cant breathe', 'cannot breathe'], severity: 'critical', label: 'Breathing difficulty' },
  { keywords: ['sudden weakness', 'one side', 'face drooping', 'slurred speech'], severity: 'critical', label: 'Possible stroke symptoms' },
  { keywords: ['fainting', 'lost consciousness', 'passed out', 'unconscious'], severity: 'high', label: 'Loss of consciousness' },
  { keywords: ['severe bleeding', 'blood loss', 'hemorrhage'], severity: 'critical', label: 'Severe bleeding' },
  { keywords: ['suicidal', 'self harm', 'kill myself', 'end my life'], severity: 'critical', label: 'Mental health crisis' },
  { keywords: ['severe abdominal pain', 'acute abdomen'], severity: 'high', label: 'Acute abdominal pain' },
  { keywords: ['high fever', 'very high fever', 'fever with rash'], severity: 'medium', label: 'High fever' },
  { keywords: ['vomiting blood', 'blood in vomit', 'hematemesis'], severity: 'critical', label: 'GI bleeding' },
  { keywords: ['severe headache', 'worst headache', 'thunderclap headache'], severity: 'high', label: 'Severe headache' },
];

export function detectRedFlags(text: string): { triggered: boolean; matchedRules: typeof redFlagRules } {
  const lower = text.toLowerCase();
  const matched = redFlagRules.filter(rule =>
    rule.keywords.some(kw => lower.includes(kw))
  );
  return { triggered: matched.length > 0, matchedRules: matched };
}

export interface LocalizedQuestion {
  id: string;
  section: string;
  question: Record<string, string>;
  quickReplies: Record<string, string[]>;
}

// SOCRATES question flow (multi-language)
export const socratesQuestions: LocalizedQuestion[] = [
  {
    id: 'chief', section: 'chief_complaint',
    question: {
      en: "What brings you to the hospital today? What is your main complaint?",
      hi: "आज आप अस्पताल क्यों आए हैं? आपकी मुख्य समस्या क्या है?",
      ta: "இன்று நீங்கள் மருத்துவமனைக்கு வந்த காரணம் என்ன? உங்கள் முக்கிய புகார் என்ன?",
      te: "ఈరోజు మీరు ఆసుపత్రికి ఎందుకు వచ్చారు? మీ ప్రధాన సమస్య ఏమిటి?",
      bn: "আজ আপনি হাসপাতালে কেন এসেছেন? আপনার প্রধান সমস্যা কী?",
      mr: "आज तुम्ही रुग्णालयात का आलात? तुमची मुख्य तक्रार काय आहे?",
    },
    quickReplies: {
      en: ['Fever', 'Headache', 'Chest pain', 'Stomach pain', 'Joint pain', 'Other'],
      hi: ['बुखार', 'सिरदर्द', 'छाती में दर्द', 'पेट दर्द', 'जोड़ों का दर्द', 'अन्य'],
      ta: ['காய்ச்சல்', 'தலைவலி', 'மார்பு வலி', 'வயிற்று வலி', 'மூட்டு வலி', 'மற்றவை'],
      te: ['జ్వరం', 'తలనొప్పి', 'ఛాతీ నొప్పి', 'కడుపు నొప్పి', 'కీళ్ల నొప్పి', 'ఇతర'],
      bn: ['জ্বর', 'মাথাব্যথা', 'বুকে ব্যথা', 'পেটে ব্যথা', 'জয়েন্টে ব্যথা', 'অন্যান্য'],
      mr: ['ताप', 'डोकेदुखी', 'छातीत दुखणे', 'पोटदुखी', 'सांधेदुखी', 'इतर'],
    },
  },
  {
    id: 'site', section: 'hpi.site',
    question: {
      en: "Can you point to exactly where you feel the problem? Which part of your body is affected?",
      hi: "क्या आप बता सकते हैं कि समस्या ठीक कहाँ है? आपके शरीर का कौन सा हिस्सा प्रभावित है?",
      ta: "நீங்கள் எந்த பகுதியில் பிரச்சினை உணர்கிறீர்கள்? உங்கள் உடலின் எந்த பகுதி பாதிக்கப்பட்டுள்ளது?",
      te: "మీరు ఎక్కడ సమస్య ఉందో చూపగలరా? మీ శరీరంలో ఏ భాగం ప్రభావితమైంది?",
      bn: "আপনি কি বলতে পারেন সমস্যাটি ঠিক কোথায়? আপনার শরীরের কোন অংশে সমস্যা?",
      mr: "तुम्हाला समस्या नेमकी कुठे जाणवते? तुमच्या शरीराचा कोणता भाग बाधित आहे?",
    },
    quickReplies: {
      en: ['Head', 'Chest', 'Abdomen', 'Left arm', 'Right leg', 'Back'],
      hi: ['सिर', 'छाती', 'पेट', 'बायां हाथ', 'दायां पैर', 'पीठ'],
      ta: ['தலை', 'மார்பு', 'வயிறு', 'இடது கை', 'வலது கால்', 'முதுகு'],
      te: ['తల', 'ఛాతీ', 'కడుపు', 'ఎడమ చేయి', 'కుడి కాలు', 'వెనుక'],
      bn: ['মাথা', 'বুক', 'পেট', 'বাম হাত', 'ডান পা', 'পিঠ'],
      mr: ['डोके', 'छाती', 'पोट', 'डावा हात', 'उजवा पाय', 'पाठ'],
    },
  },
  {
    id: 'onset', section: 'hpi.onset',
    question: {
      en: "When did this problem start? Was it sudden or gradual?",
      hi: "यह समस्या कब शुरू हुई? क्या यह अचानक थी या धीरे-धीरे?",
      ta: "இந்த பிரச்சினை எப்போது தொடங்கியது? திடீரென தொடங்கியதா அல்லது மெதுவாகவா?",
      te: "ఈ సమస్య ఎప్పుడు మొదలైంది? అకస్మాత్తుగానా లేక నెమ్మదిగానా?",
      bn: "এই সমস্যাটি কখন শুরু হয়েছিল? এটা কি হঠাৎ নাকি ধীরে ধীরে?",
      mr: "ही समस्या कधी सुरू झाली? हे अचानक की हळूहळू?",
    },
    quickReplies: {
      en: ['Today', 'Yesterday', 'Few days ago', 'Last week', 'Over a month', 'Long time ago'],
      hi: ['आज', 'कल', 'कुछ दिन पहले', 'पिछले हफ्ते', 'एक महीने से ज्यादा', 'बहुत पहले'],
      ta: ['இன்று', 'நேற்று', 'சில நாட்கள் முன்', 'கடந்த வாரம்', 'ஒரு மாதத்திற்கு மேல்', 'நீண்ட காலமாக'],
      te: ['ఈరోజు', 'నిన్న', 'కొన్ని రోజుల క్రితం', 'గత వారం', 'నెలకు పైగా', 'చాలా కాలం క్రితం'],
      bn: ['আজ', 'গতকাল', 'কয়েক দিন আগে', 'গত সপ্তাহে', 'এক মাসের বেশি', 'অনেক আগে'],
      mr: ['आज', 'काल', 'काही दिवसांपूर्वी', 'गेल्या आठवड्यात', 'एक महिन्यापेक्षा जास्त', 'खूप आधी'],
    },
  },
  {
    id: 'character', section: 'hpi.character',
    question: {
      en: "How would you describe the sensation? Is it a sharp pain, dull ache, burning, or throbbing?",
      hi: "आप यह अनुभूति कैसे वर्णन करेंगे? क्या यह तेज दर्द, मंद दर्द, जलन, या धड़कन है?",
      ta: "நீங்கள் எப்படி உணர்கிறீர்கள்? கூர்மையான வலி, மந்தமான வலி, எரிச்சல், அல்லது துடிப்பு?",
      te: "మీరు ఎలా అనుభూతి చెందుతున్నారు? ఇది తీవ్రమైన నొప్పి, మందకొక్క నొప్పి, మంట, లేక స్పందనా?",
      bn: "আপনি এই অনুভূতি কীভাবে বর্ণনা করবেন? এটা কি তীব্র ব্যথা, মন্দ ব্যথা, জ্বালা, নাকি স্পন্দন?",
      mr: "तुम्हाला कसे जाणवते? हे तीव्र वेदना, कुरकुरीत वेदना, जळजळी, की धडधड?",
    },
    quickReplies: {
      en: ['Sharp pain', 'Dull ache', 'Burning', 'Throbbing', 'Cramping', 'Numbness'],
      hi: ['तेज दर्द', 'मंद दर्द', 'जलन', 'धड़कन', 'ऐंठन', 'सुन्नता'],
      ta: ['கூர்மையான வலி', 'மந்தமான வலி', 'எரிச்சல்', 'துடிப்பு', 'பிடிப்பு', 'உணர்வின்மை'],
      te: ['తీవ్ర నొప్పి', 'మందకొక్క నొప్పి', 'మంట', 'స్పందన', 'పుచ్చుట', 'తిమ్మిరు'],
      bn: ['তীব্র ব্যথা', 'মন্দ ব্যথা', 'জ্বালা', 'স্পন্দন', 'খিঁচুনি', 'অবশতা'],
      mr: ['तीव्र वेदना', 'कुरकुरीत वेदना', 'जळजळी', 'धडधड', 'झटके', 'सुन्नपणा'],
    },
  },
  {
    id: 'radiation', section: 'hpi.radiation',
    question: {
      en: "Does the sensation spread to any other part of your body?",
      hi: "क्या यह अनुभूति आपके शरीर के किसी और हिस्से में फैलती है?",
      ta: "இந்த உணர்வு உங்கள் உடலின் வேறு பகுதிகளுக்கு பரவுகிறதா?",
      te: "ఈ అనుభూతి మీ శరీరంలోని ఇతర భాగాలకు వ్యాపిస్తుందా?",
      bn: "এই অনুভূতিটি কি আপনার শরীরের অন্য কোনো অংশে ছড়ায়?",
      mr: "ही जाणीव तुमच्या शरीराच्या इतर कोणत्याही भागात पसरते का?",
    },
    quickReplies: {
      en: ['No, stays in one place', 'Spreads to arm', 'Spreads to back', 'Spreads to jaw', 'Spreads to legs'],
      hi: ['नहीं, एक जगह रहती है', 'हाथ में फैलती है', 'पीठ में फैलती है', 'जबड़े में फैलती है', 'पैरों में फैलती है'],
      ta: ['இல்லை, ஒரே இடத்தில் உள்ளது', 'கைக்கு பரவுகிறது', 'முதுகிற்கு பரவுகிறது', 'தாடைக்கு பரவுகிறது', 'கால்களுக்கு பரவுகிறது'],
      te: ['లేదు, ఒకే చోట ఉంది', 'చేయికి వ్యాపిస్తుంది', 'వెనుకకు వ్యాపిస్తుంది', 'దవడకు వ్యాపిస్తుంది', 'కాళ్లకు వ్యాపిస్తుంది'],
      bn: ['না, এক জায়গায় থাকে', 'হাতে ছড়ায়', 'পিঠে ছড়ায়', 'চোয়ালে ছড়ায়', 'পায়ে ছড়ায়'],
      mr: ['नाही, एकाच जागी राहते', 'हातात पसरते', 'पाठीत पसरते', 'जबड्यात पसरते', 'पायांत पसरते'],
    },
  },
  {
    id: 'associations', section: 'hpi.associations',
    question: {
      en: "Do you have any other symptoms along with this? Like nausea, dizziness, or sweating?",
      hi: "क्या इसके साथ कोई और लक्षण भी हैं? जैसे जी मिचलाना, चक्कर, या पसीना?",
      ta: "இதனுடன் வேறு ஏதேனும் அறிகுறிகள் உள்ளதா? குமட்டல், தலைச்சுற்றல், அல்லது வியர்வை?",
      te: 'దీనితో పాటు మరేవేరు లక్షణాలు ఉన్నాయా? వాంతుల భావన, తల తిరగడం, లేక చెమట?',
      bn: "এর সাথে অন্য কোনো লক্ষণ আছে কি? যেমন বমি বমি ভাব, মাথা ঘোরা, বা ঘাম?",
      mr: "याच्याबरोबर इतर कोणतेही लक्षणे आहेत का? जसे भस्मक, चक्कर, की घाम?",
    },
    quickReplies: {
      en: ['Nausea', 'Dizziness', 'Sweating', 'Vomiting', 'Fever', 'No other symptoms'],
      hi: ['जी मिचलाना', 'चक्कर', 'पसीना', 'उल्टी', 'बुखार', 'कोई और लक्षण नहीं'],
      ta: ['குமட்டல்', 'தலைச்சுற்றல்', 'வியர்வை', 'வாந்தி', 'காய்ச்சல்', 'வேறு அறிகுறிகள் இல்லை'],
      te: ['వాంతుల భావన', 'తల తిరగడం', 'చెమట', 'వాంతులు', 'జ్వరం', 'ఇతర లక్షణాలు లేవు'],
      bn: ['বমি বমি ভাব', 'মাথা ঘোরা', 'ঘাম', 'বমি', 'জ্বর', 'অন্য কোনো লক্ষণ নেই'],
      mr: ['भस्मक', 'चक्कर', 'घाम', 'उलटी', 'ताप', 'इतर लक्षणे नाहीत'],
    },
  },
  {
    id: 'time', section: 'hpi.time',
    question: {
      en: "Does the problem stay all the time, or does it come and go? Is it worse at any particular time?",
      hi: "क्या समस्या हमेशा रहती है, या आती-जाती है? क्या किसी विशेष समय पर यह ज्यादा होती है?",
      ta: "பிரச்சினை எப்போதும் இருக்கிறதா, அல்லது வருகிறது போகிறதா? எப்போதென்றால் அதிகமாக இருக்கிறது?",
      te: 'సమస్య ఎప్పుడూ ఉంటుందా, లేక వస్తుందా పోతుందా? ఏ మార్పు సమయంలో ఎక్కువగా ఉంటుందా?',
      bn: "সমস্যাটি কি সব সময় থাকে, নাকি আসে-যায়? কোনো বিশেষ সময়ে কি এটা বেশি হয়?",
      mr: "समस्या नेहमी असते की येते-जाते? विशिष्ट वेळी जास्त होते का?",
    },
    quickReplies: {
      en: ['Constant', 'Comes and goes', 'Worse at night', 'Worse in morning', 'Worse after eating', 'Worse with movement'],
      hi: ['लगातार', 'आता-जाता है', 'रात में ज्यादा', 'सुबह ज्यादा', 'खाने के बाद ज्यादा', 'हिलने से ज्यादा'],
      ta: ['தொடர்ந்து', 'வருகிறது போகிறது', 'இரவில் அதிகம்', 'காலையில் அதிகம்', 'சாப்பாட்டிற்கு பின் அதிகம்', 'நகர்வதால் அதிகம்'],
      te: ['నిరంతరం', 'వస్తుంది పోతుంది', 'రాత్రి ఎక్కువ', 'ఉదయం ఎక్కువ', 'తిన్న తర్వాత ఎక్కువ', 'కదిలితే ఎక్కువ'],
      bn: ['সব সময়', 'আসে-যায়', 'রাতে বেশি', 'সকালে বেশি', 'খাওয়ার পর বেশি', 'নড়াচড়ায় বেশি'],
      mr: ['सतत', 'येते-जाते', 'रात्री जास्त', 'सकाळी जास्त', 'जेवणानंतर जास्त', 'हालचालीने जास्त'],
    },
  },
  {
    id: 'exacerbating', section: 'hpi.exacerbating',
    question: {
      en: "What makes the problem worse? Does any activity or position increase your discomfort?",
      hi: "किस चीज से समस्या बढ़ती है? क्या कोई गतिविधि या स्थिति आपकी परेशानी बढ़ाती है?",
      ta: "எது பிரச்சினையை அதிகப்படுத்துகிறது? ஏதேனும் செயல் அல்லது நிலை உங்கள் அசௌகரியத்தை அதிகப்படுத்துகிறதா?",
      te: 'ఏమి సమస్యను పెంచుతుంది? ఏ కార్యం లేక స్థితి మీ ఇబ్బందిని పెంచుతుంది?',
      bn: "কী জিনিস সমস্যা বাড়ায়? কোনো কাজ বা অবস্থান কি আপনার অস্বস্তি বাড়ায়?",
      mr: "कशामुळे समस्या वाढते? कोणती क्रिया किंवा स्थिती तुमची त्रास वाढवते?",
    },
    quickReplies: {
      en: ['Movement', 'Eating', 'Lying down', 'Stress', 'Cold weather', 'Nothing makes it worse'],
      hi: ['हिलना-डुलना', 'खाना', 'लेटना', 'तनाव', 'ठंड', 'कुछ नहीं बढ़ाता'],
      ta: ['நகர்தல்', 'சாப்பிடுதல்', 'படுத்தல்', 'மன அழுத்தம்', 'குளிர்', 'எதுவும் அதிகப்படுத்தவில்லை'],
      te: ['కదలిక', 'తినడం', 'పడుకోవడం', 'ఒత్తిడి', 'చలి', 'ఏదీ పెంచదు'],
      bn: ['নড়াচড়া', 'খাওয়া', 'শুয়ে থাকা', 'মানসিক চাপ', 'ঠান্ডা', 'কিছুই বাড়ায় না'],
      mr: ['हालचाल', 'जेवण', 'झोपणे', 'तणाव', 'थंडी', 'काहीही वाढवत नाही'],
    },
  },
  {
    id: 'relieving', section: 'hpi.relieving',
    question: {
      en: "What makes it better? Does rest, medication, or any position give you relief?",
      hi: "किस चीज से राहत मिलती है? क्या आराम, दवा, या कोई स्थिति राहत देती है?",
      ta: "எது நன்மை செய்கிறது? ஓய்வு, மருந்து, அல்லது ஏதேனும் நிலை நிவாரணம் தருகிறதா?",
      te: 'ఏమి మెరుగుపరుస్తుంది? విశ్రాంత, మందు, లేక ఏ స్థితి ఉపశమనం ఇస్తుందా?',
      bn: "কী জিনিসে ভালো লাগে? বিশ্রাম, ওষুধ, বা কোনো অবস্থান কি স্বস্তি দেয়?",
      mr: "कशामुळे बरे वाटते? विश्रांती, औषध, किंवा कोणतीही स्थिती आराम देते का?",
    },
    quickReplies: {
      en: ['Rest', 'Medication', 'Sitting up', 'Cold compress', 'Warm compress', 'Nothing helps'],
      hi: ['आराम', 'दवा', 'बैठना', 'ठंडी सिकाई', 'गर्म सिकाई', 'कुछ काम नहीं करता'],
      ta: ['ஓய்வு', 'மருந்து', 'உட்கார்வது', 'குளிர் ஒத்தடம்', 'சூடான ஒத்தடம்', 'எதுவும் உதவாது'],
      te: ['విశ్రాంత', 'మందు', 'కూర్చోవడం', 'చల్లని సంచి', 'వేడి సంచి', 'ఏదీ సహాయించదు'],
      bn: ['বিশ্রাম', 'ওষুধ', 'বসা', 'ঠান্ডা সেঁক', 'গরম সেঁক', 'কিছুই সাহায্য করে না'],
      mr: ['विश्रांती', 'औषध', 'बसणे', 'थंड शेक', 'गरम शेक', 'काहीही मदत करत नाही'],
    },
  },
  {
    id: 'severity', section: 'hpi.severity',
    question: {
      en: "On a scale of 1 to 10, how would you rate your discomfort? Where 1 is mild and 10 is the worst you have ever felt.",
      hi: "1 से 10 के पैमाने पर, अपनी परेशानी को कैसे रेट करेंगे? जहाँ 1 हल्का है और 10 सबसे ज्यादा।",
      ta: "1 முதல் 10 வரை, உங்கள் அசௌகரியத்தை எப்படி மதிப்பிடுவீர்கள்? 1 மென்மையானது, 10 மிக மோசம்.",
      te: '1 నుండి 10 స్కేలులో, మీ ఇబ్బందిని ఎలా రేట్ చేస్తారు? 1 తేలిక, 10 అత్యంత తీవ్ర.',
      bn: "১ থেকে ১০ স্কেলে, আপনার অস্বস্তি কতটা? যেখানে ১ হালকা এবং ১০ সবচেয়ে খারাপ।",
      mr: "१ ते १० च्या पट्टीवर, तुमचा त्रास किती आहे? जिथे १ हलका आणि १० सर्वात जास्त.",
    },
    quickReplies: {
      en: ['1-2 (Mild)', '3-4 (Moderate)', '5-6 (Significant)', '7-8 (Severe)', '9-10 (Very severe)'],
      hi: ['1-2 (हल्का)', '3-4 (मध्यम)', '5-6 (ज्यादा)', '7-8 (गंभीर)', '9-10 (बहुत ज्यादा)'],
      ta: ['1-2 (மென்மை)', '3-4 (மிதமான)', '5-6 (கணிசமான)', '7-8 (கடுமையான)', '9-10 (மிக கடுமையான)'],
      te: ['1-2 (తేలిక)', '3-4 (మధ్యమ)', '5-6 (గణనీయ)', '7-8 (తీవ్ర)', '9-10 (చాలా తీవ్ర)'],
      bn: ['1-2 (হালকা)', '3-4 (মাঝারি)', '5-6 (উল্লেখযোগ্য)', '7-8 (তীব্র)', '9-10 (অত্যন্ত তীব্র)'],
      mr: ['1-2 (हलका)', '3-4 (मध्यम)', '5-6 (लक्षणीय)', '7-8 (तीव्र)', '9-10 (अतिशय तीव्र)'],
    },
  },
  {
    id: 'past_medical', section: 'past_medical',
    question: {
      en: "Do you have any existing medical conditions like diabetes, high blood pressure, or thyroid problems?",
      hi: "क्या आपको कोई मौजूदा बीमारी है जैसे डायबिटीज, उच्च रक्तचाप, या थायराइड?",
      ta: "நீரிழிவு, உயர் இரத்த அழுத்தம், அல்லது தைராய்டு போன்ற ஏதேனும் நோய்கள் உள்ளதா?",
      te: 'మధుమేహం, అధిక రక్తపోటు, లేక థైరాయిడ్ వంటి వ్యాధులు మీకు ఉన్నాయా?',
      bn: "আপনার কি ডায়াবেটিস, উচ্চ রক্তচাপ, বা থাইরয়েডের মতো কোনো বিদ্যমান রোগ আছে?",
      mr: "तुम्हाला मधुमेह, उच्च रक्तदाब, किंवा थायरॉइडसारखा कोणता तरी आजार आहे का?",
    },
    quickReplies: {
      en: ['Diabetes', 'Hypertension', 'Thyroid', 'Asthma', 'Heart disease', 'None'],
      hi: ['डायबिटीज', 'उच्च रक्तचाप', 'थायराइड', 'अस्थमा', 'हृदय रोग', 'कोई नहीं'],
      ta: ['நீரிழிவு', 'உயர் இரத்த அழுத்தம்', 'தைராய்டு', 'ஆஸ்துமா', 'இதய நோய்', 'இல்லை'],
      te: ['మధుమేహం', 'అధిక రక్తపోటు', 'థైరాయిడ్', 'ఆస్త్మా', 'గుండె జబ్బు', 'లేవు'],
      bn: ['ডায়াবেটিস', 'উচ্চ রক্তচাপ', 'থাইরয়েড', 'হাঁপানি', 'হৃদরোগ', 'কোনোটিই নয়'],
      mr: ['मधुमेह', 'उच्च रक्तदाब', 'थायरॉइड', 'दमा', 'हृदयरोग', 'काहीही नाही'],
    },
  },
  {
    id: 'past_surgical', section: 'past_surgical',
    question: {
      en: "Have you had any surgeries or operations in the past?",
      hi: "क्या आपके पहले कोई सर्जरी या ऑपरेशन हुआ है?",
      ta: "கடந்த காலத்தில் ஏதேனும் அறுவை சிகிச்சை செய்துள்ளீர்களா?",
      te: 'గతంలో మీరు ఏవైనా శస్త్రచికిత్సలు చేయించుకున్నారా?',
      bn: "আপনার কি অতীতে কোনো সার্জারি বা অপারেশন হয়েছে?",
      mr: "तुमची आधी कोणतीही शस्त्रक्रिया झाली आहे का?",
    },
    quickReplies: {
      en: ['Yes, major surgery', 'Yes, minor procedure', 'No surgeries', 'Not sure'],
      hi: ['हाँ, बड़ी सर्जरी', 'हाँ, छोटी प्रक्रिया', 'कोई सर्जरी नहीं', 'पता नहीं'],
      ta: ['ஆம், பெரிய அறுவை', 'ஆம், சிறிய சிகிச்சை', 'அறுவை இல்லை', 'தெரியவில்லை'],
      te: ['అవును, పెద్ద శస్త్రచికిత్స', 'అవును, చిన్న ప్రక్రియ', 'శస్త్రచికిత్సలు లేవు', 'ఖచ్చితంగా తెలియదు'],
      bn: ['হ্যাঁ, বড় সার্জারি', 'হ্যাঁ, ছোট প্রক্রিয়া', 'কোনো সার্জারি নেই', 'নিশ্চিত নই'],
      mr: ['होय, मोठी शस्त्रक्रिया', 'होय, लहान प्रक्रिया', 'शस्त्रक्रिया नाही', 'खात्री नाही'],
    },
  },
  {
    id: 'allergies', section: 'drug_allergy',
    question: {
      en: "Are you allergic to any medicines, foods, or other substances?",
      hi: "क्या आपको किसी दवा, खाने, या किसी और चीज से एलर्जी है?",
      ta: "ஏதேனும் மருந்துகள், உணவு, அல்லது பொருட்களுக்கு ஒவ்வாமை உள்ளதா?",
      te: 'మీకు ఏవైనా మందులు, ఆహారం, లేక పదార్థాలకు అలర్జీ ఉందా?',
      bn: "আপনার কি কোনো ওষুধ, খাবার, বা অন্য কোনো পদার্থে অ্যালার্জি আছে?",
      mr: "तुम्हाला कोणत्याही औषधांची, खाद्यपदार्थांची किंवा पदार्थांची अॅलर्जी आहे का?",
    },
    quickReplies: {
      en: ['No allergies', 'Penicillin', 'Sulfa drugs', 'Aspirin', 'Food allergy', 'Not sure'],
      hi: ['कोई एलर्जी नहीं', 'पेनिसिलिन', 'सल्फा दवाएं', 'एस्पिरिन', 'खाने की एलर्जी', 'पता नहीं'],
      ta: ['ஒவ்வாமை இல்லை', 'பெனிசிலின்', 'சல்ஃபா மருந்துகள்', 'ஆஸ்பிரின்', 'உணவு ஒவ்வாமை', 'தெரியவில்லை'],
      te: ['అలర్జీ లేదు', 'పెనిసిలిన్', 'సల్ఫా మందులు', 'ఆస్పిరిన్', 'ఆహార అలర్జీ', 'ఖచ్చితంగా తెలియదు'],
      bn: ['অ্যালার্জি নেই', 'পেনিসিলিন', 'সালফা ওষুধ', 'অ্যাসপিরিন', 'খাবার অ্যালার্জি', 'নিশ্চিত নই'],
      mr: ['अॅलर्जी नाही', 'पेनिसिलिन', 'सल्फा औषधे', 'अॅस्पिरिन', 'अन्न अॅलर्जी', 'खात्री नाही'],
    },
  },
  {
    id: 'family', section: 'family_history',
    question: {
      en: "Does anyone in your family have conditions like diabetes, heart disease, or high blood pressure?",
      hi: "क्या आपके परिवार में किसी को डायबिटीज, हृदय रोग, या उच्च रक्तचाप है?",
      ta: "உங்கள் குடும்பத்தில் யாருக்கேனும் நீரிழிவு, இதய நோய், அல்லது உயர் இரத்த அழுத்தம் உள்ளதா?",
      te: 'మీ కుటుంబంలో ఎవరికైనా మధుమేహం, గుండె జబ్బు, లేక అధిక రక్తపోటు ఉందా?',
      bn: "আপনার পরিবারে কারও কি ডায়াবেটিস, হৃদরোগ, বা উচ্চ রক্তচাপ আছে?",
      mr: "तुमच्या कुटुंबात कोणाला मधुमेह, हृदयरोग, किंवा उच्च रक्तदाब आहे का?",
    },
    quickReplies: {
      en: ['Diabetes in family', 'Heart disease in family', 'BP in family', 'Cancer in family', 'No family history', 'Not sure'],
      hi: ['परिवार में डायबिटीज', 'परिवार में हृदय रोग', 'परिवार में बीपी', 'परिवार में कैंसर', 'कोई पारिवारिक इतिहास नहीं', 'पता नहीं'],
      ta: ['குடும்பத்தில் நீரிழிவு', 'குடும்பத்தில் இதய நோய்', 'குடும்பத்தில் ரத்த அழுத்தம்', 'குடும்பத்தில் புற்றுநோய்', 'குடும்ப வரலாறு இல்லை', 'தெரியவில்லை'],
      te: ['కుటుంబంలో మధుమేహం', 'కుటుంబంలో గుండె జబ్బు', 'కుటుంబంలో బిపి', 'కుటుంబంలో క్యాన్సర్', 'కుటుంబ చరిత్ర లేదు', 'ఖచ్చితంగా తెలియదు'],
      bn: ['পরিবারে ডায়াবেটিস', 'পরিবারে হৃদরোগ', 'পরিবারে বিপি', 'পরিবারে ক্যানসার', 'পারিবারিক ইতিহাস নেই', 'নিশ্চিত নই'],
      mr: ['कुटुंबात मधुमेह', 'कुटुंबात हृदयरोग', 'कुटुंबात बीपी', 'कुटुंबात कॅन्सर', 'कौटुंबिक इतिहास नाही', 'खात्री नाही'],
    },
  },
  {
    id: 'personal', section: 'personal_history',
    question: {
      en: "Do you smoke, consume alcohol, or use tobacco products?",
      hi: "क्या आप धूम्रपान करते हैं, शराब पीते हैं, या तंबाकू का उपयोग करते हैं?",
      ta: "நீங்கள் புகையிலை பழக்கம், மது அருந்துதல், அல்லது பான் பரக் பொருட்கள் பயன்படுத்துகிறீர்களா?",
      te: 'మీరు పొగాకు తాగుతారా, మద్యం తాగుతారా, లేక పొగాకు ఉత్పత్తులు వాడుతారా?',
      bn: "আপনি কি ধূমপান করেন, মদ পান করেন, বা তামাক ব্যবহার করেন?",
      mr: "तुम्ही धूम्रपान करता, दारू पिता, किंवा तंबाखू वापरता का?",
    },
    quickReplies: {
      en: ['Non-smoker', 'Smoker', 'Alcohol consumer', 'Tobacco user', 'Former smoker', 'None of these'],
      hi: ['धूम्रपान नहीं', 'धूम्रपान करता हूं', 'शराब पीता हूं', 'तंबाकू उपयोग', 'पूर्व धूम्रपानकर्ता', 'इनमें से कोई नहीं'],
      ta: ['புகையிலை இல்லை', 'புகையிலை பழக்கம்', 'மது அருந்துபவர்', 'பான் பரக் பயன்பாடு', 'முன்னாள் புகையிலையாளர்', 'இவை எதுவும் இல்லை'],
      te: ['పొగ తాగను', 'పొగ తాగుతాను', 'మద్యం తాగుతాను', 'పొగాకు వాడతాను', 'మాజీ స్మోకర్', 'వీటిలో ఏదీ కాదు'],
      bn: ['ধূমপান করি না', 'ধূমপান করি', 'মদ পান করি', 'তামাক ব্যবহার', 'পূর্বে ধূমপান করতাম', 'এগুলোর কোনোটিই নয়'],
      mr: ['धूम्रपान करत नाही', 'धूम्रपान करतो', 'दारू पितो', 'तंबाखू वापरतो', 'माजी धूम्रपानकर्ता', 'यापैकी काहीही नाही'],
    },
  },
];

// AYUSH / Dashavidha Pariksha questions (multi-language)
export const ayushQuestions: LocalizedQuestion[] = [
  {
    id: 'prakriti', section: 'ayush.prakriti',
    question: {
      en: "What is your body constitution (Prakriti)? Do you feel you are more Vata (slender, energetic), Pitta (medium build, intense), or Kapha (solid, calm) type?",
      hi: "आपकी शरीर प्रकृति क्या है? क्या आप वात (पतला, ऊर्जावान), पित्त (मध्यम, तीव्र), या कफ (ठोस, शांत) प्रकार के हैं?",
      ta: "உங்கள் உடல் அமைப்பு (பிரகிருதி) என்ன? வாத, பித்த, அல்லது கப வகையா?",
      te: 'మీ శరీర స్వభావం (ప్రకృతి) ఏమిటి? వాత, పిత్త, లేక కఫ రకా? వంటివా?',
      bn: "আপনার শরীরের প্রকৃতি কী? আপনি কি বাত, পিত্ত, নাকি কফ প্রকৃতির?",
      mr: "तुमची शरीर प्रकृती काय आहे? तुम्ही वात, पित्त, की कफ प्रकृतीचे आहात?",
    },
    quickReplies: {
      en: ['Vata', 'Pitta', 'Kapha', 'Vata-Pitta', 'Pitta-Kapha', 'Not sure'],
      hi: ['वात', 'पित्त', 'कफ', 'वात-पित्त', 'पित्त-कफ', 'पता नहीं'],
      ta: ['வாத', 'பித்த', 'கப', 'வாத-பித்த', 'பித்த-கப', 'தெரியவில்லை'],
      te: ['వాత', 'పిత్త', 'కఫ', 'వాత-పిత్త', 'పిత్త-కఫ', 'ఖచ్చితంగా తెలియదు'],
      bn: ['বাত', 'পিত্ত', 'কফ', 'বাত-পিত্ত', 'পিত্ত-কফ', 'নিশ্চিত নই'],
      mr: ['वात', 'पित्त', 'कफ', 'वात-पित्त', 'पित्त-कफ', 'खात्री नाही'],
    },
  },
  {
    id: 'vikriti', section: 'ayush.vikriti',
    question: {
      en: "What is your current imbalance (Vikriti)? Do you feel any particular dosha is aggravated right now?",
      hi: "आपकी वर्तमान असंतुलन (विकृति) क्या है? क्या आपको कोई विशेष दोष बढ़ा हुआ लगता है?",
      ta: "உங்கள் தற்போதைய சமநிலையின்மை (விகிருதி) என்ன? ஏதேனும் தோஷம் அதிகரித்துள்ளதா?",
      te: 'మీ ప్రస్తుత అసమతుల్యత (వికృతి) ఏమిటి? ఏ దోషం పెరిగిందా?',
      bn: "আপনার বর্তমান অসামঞ্জস্য (বিকৃতি) কী? কোনো দোষ কি বৃদ্ধি পেয়েছে?",
      mr: "तुमची सध्याची असंतुलन स्थिती (विकृती) काय आहे? कोणता तरी दोष वाढला आहे का?",
    },
    quickReplies: {
      en: ['Vata aggravated', 'Pitta aggravated', 'Kapha aggravated', 'Balanced', 'Not sure'],
      hi: ['वात बढ़ा हुआ', 'पित्त बढ़ा हुआ', 'कफ बढ़ा हुआ', 'संतुलित', 'पता नहीं'],
      ta: ['வாத அதிகரிப்பு', 'பித்த அதிகரிப்பு', 'கப அதிகரிப்பு', 'சமநிலை', 'தெரியவில்லை'],
      te: ['వాత పెరిగింది', 'పిత్త పెరిగింది', 'కఫ పెరిగింది', 'సమతుల్యం', 'ఖచ్చితంగా తెలియదు'],
      bn: ['বাত বৃদ্ধি', 'পিত্ত বৃদ্ধি', 'কফ বৃদ্ধি', 'সুসমতা', 'নিশ্চিত নই'],
      mr: ['वात वाढला', 'पित्त वाढला', 'कफ वाढला', 'संतुलित', 'खात्री नाही'],
    },
  },
  {
    id: 'sara', section: 'ayush.sara',
    question: {
      en: "How is the quality of your tissues (Sara)? Do you feel your body is well-nourished and strong?",
      hi: "आपके ऊतकों की गुणवत्ता (सार) कैसी है? क्या आपका शरीर अच्छी तरह पोषित और मजबूत है?",
      ta: "உங்கள் திசுக்களின் தரம் (சார) எப்படி உள்ளது? உங்கள் உடல் நன்கு ஊட்டமாகவும் வலுவாகவும் உள்ளதா?",
      te: 'మీ కణజాలం నాణ్యత (సార) ఎలా ఉంది? మీ శరీరం బాగా పోషితమై బలంగా ఉందా?',
      bn: "আপনার টিস্যুর গুণমান (সার) কেমন? আপনার শরীর কি ভালো পুষ্ট এবং শক্তিশালী?",
      mr: "तुमच्या ऊतकांची गुणवत्ता (सार) कशी आहे? तुमचे शरीर चांगले पोषित आणि मजबूत आहे का?",
    },
    quickReplies: {
      en: ['Excellent', 'Good', 'Average', 'Poor', 'Very weak'],
      hi: ['उत्कृष्ट', 'अच्छा', 'औसत', 'कमजोर', 'बहुत कमजोर'],
      ta: ['சிறந்த', 'நல்ல', 'சராசரி', 'மோசம்', 'மிகவும் பலஹீனம்'],
      te: ['అద్భుత', 'మంచి', 'సగటు', 'తక్కువ', 'చాలా బలహీనం'],
      bn: ['চমৎকার', 'ভালো', 'গড়', 'দুর্বল', 'অত্যন্ত দুর্বল'],
      mr: ['उत्कृष्ट', 'चांगले', 'सरासरी', 'दुबळे', 'अतिशय दुबळे'],
    },
  },
  {
    id: 'samhanana', section: 'ayush.samhanana',
    question: {
      en: "How is your body build and compactness (Samhanana)? Is your body well-proportioned and compact?",
      hi: "आपकी शरीर संरचना और कॉम्पैक्टनेस (संहनन) कैसी है? क्या आपका शरीर सुडौल और कॉम्पैक्ट है?",
      ta: "உங்கள் உடல் அமைப்பு (சம்ஹனன) எப்படி உள்ளது? உங்கள் உடல் நன்கு விகிதாசாரமாக உள்ளதா?",
      te: 'మీ శరీర నిర్మాణం (సంహనన) ఎలా ఉంది? మీ శరీరం సమన్వయంగా ఉందా?',
      bn: "আপনার শরীরের গঠন (সংহনন) কেমন? আপনার শরীর কি সুঠাম এবং কম্প্যাক্ট?",
      mr: "तुमच्या शरीराची रचना (संहनन) कशी आहे? तुमचे शरीर योग्य प्रमाणात आहे का?",
    },
    quickReplies: {
      en: ['Well-built', 'Compact', 'Average', 'Loose build', 'Frail'],
      hi: ['अच्छी बनावट', 'कॉम्पैक्ट', 'औसत', 'ढीली बनावट', 'कमजोर'],
      ta: ['நன்கு கட்டமைப்பு', 'கம்பாக்ட்', 'சராசரி', 'தளர்வான', 'பலஹீனம்'],
      te: ['బాగా నిర్మిత', 'కంపాక్ట్', 'సగటు', 'వదులైన', 'బలహీనం'],
      bn: ['সুঠাম', 'কম্প্যাক্ট', 'গড়', 'ঢোলা', 'দুর্বল'],
      mr: ['चांगली रचना', 'कॉम्पॅक्ट', 'सरासरी', 'सैलसर', 'दुबळे'],
    },
  },
  {
    id: 'pramana', section: 'ayush.pramana',
    question: {
      en: "What are your body measurements (Pramana)? Is your height-to-weight ratio proportionate?",
      hi: "आपकी शरीर माप (प्रमाण) क्या है? क्या आपका ऊंचाई-वजन अनुपात सही है?",
      ta: "உங்கள் உடல் அளவீடுகள் (பிரமாண) என்ன? உயரம்-எடை விகிதம் சரியா?",
      te: 'మీ శరీర కొలమానాలు (ప్రమాణ) ఏమిటి? ఎత్తు-బరువు నిష్పత్తి సరైనదా?',
      bn: "আপনার শরীরের পরিমাপ (প্রমাণ) কী? উচ্চতা-ওজন অনুপাত কি সঠিক?",
      mr: "तुमच्या शरीराचे माप (प्रमाण) काय आहे? उंची-वजन गुणोत्तर योग्य आहे का?",
    },
    quickReplies: {
      en: ['Proportionate', 'Slightly overweight', 'Slightly underweight', 'Obese', 'Very thin'],
      hi: ['सुडौल', 'थोड़ा मोटा', 'थोड़ा पतला', 'बहुत मोटा', 'बहुत पतला'],
      ta: ['விகிதாசாரமான', 'சற்று அதிக எடை', 'சற்று குறைவான எடை', 'பருமனான', 'மிகவும் மெலிந்த'],
      te: ['సమన్వయం', 'కొంచెం బరువు', 'కొంచెం తేలిక', 'స్థూలకాయం', 'చాలా సన్నం'],
      bn: ['সুঠাম', 'সামান্য বেশি ওজন', 'সামান্য কম ওজন', 'স্থূল', 'অত্যন্ত রোগা'],
      mr: ['योग्य', 'थोडे जास्त वजन', 'थोडे कमी वजन', 'जाड', 'अतिशय सडपात'],
    },
  },
  {
    id: 'satmya', section: 'ayush.satmya',
    question: {
      en: "What foods and habits are you accustomed to (Satmya)? Do you tolerate spicy, cold, or heavy foods well?",
      hi: "आप किन खाद्य पदार्थों और आदतों के आदी हैं (सात्म्य)? क्या आप तीखा, ठंडा, या भारी भोजन अच्छी तरह सह लेते हैं?",
      ta: "நீங்கள் எந்த உணவு மற்றும் பழக்கங்களுக்கு பழக்கப்பட்டவர் (சாத்ம்யம்)? காரம், குளிர், அல்லது கனமான உணவை தாங்க முடியுமா?",
      te: 'మీరు ఏ ఆహారం మరియు అలవాట్లకు అలవాటు పడ్డారు (సాత్మ్య)? కారం, చల్లని, లేక భారీ ఆహారం తట్టుకోగలరా?',
      bn: "আপনি কী ধরনের খাবার ও অভ্যাসে অভ্যস্ত (সাত্ম্য)? ঝাল, ঠান্ডা, বা ভারী খাবার সহ্য করতে পারেন?",
      mr: "तुम्ही कोणत्या खाद्यपदार्थांच्या आणि सवयींच्या (सात्म्य) आदी आहात? तिखट, थंड, किंवा जड जेवण सहन करू शकता का?",
    },
    quickReplies: {
      en: ['Tolerate all', 'Prefer warm food', 'Prefer mild food', 'Sensitive to cold', 'Sensitive to spicy'],
      hi: ['सब सह लेता हूं', 'गरम भोजन पसंद', 'हल्का भोजन पसंद', 'ठंड से संवेदनशील', 'तीखे से संवेदनशील'],
      ta: ['அனைத்தையும் தாங்குவேன்', 'சூடான உணவு விரும்புவேன்', 'மென்மையான உணவு', 'குளிர் உணர்திறன்', 'காரம் உணர்திறன்'],
      te: ['అన్నీ తట్టుకోగలను', 'వేడి ఆహారం ఇష్టం', 'తేలిక ఆహారం', 'చలి సున్నితం', 'కారం సున్నితం'],
      bn: ['সব সহ্য হয়', 'গরম খাবার পছন্দ', 'হালকা খাবার পছন্দ', 'ঠান্ডায় সংবেদনশীল', 'ঝালে সংবেদনশীল'],
      mr: ['सर्व सहन होते', 'गरम जेवण आवडीचे', 'हलके जेवण आवडीचे', 'थंडीसह संवेदनशील', 'तिखटासह संवेदनशील'],
    },
  },
  {
    id: 'sattva', section: 'ayush.sattva',
    question: {
      en: "How is your mental state and temperament (Sattva)? Are you generally calm, anxious, or easily disturbed?",
      hi: "आपकी मानसिक स्थिति और स्वभाव (सत्त्व) कैसा है? क्या आप आमतौर पर शांत, चिंतित, या आसानी से विचलित होते हैं?",
      ta: "உங்கள் மன நிலை மற்றும் குணம் (சத்த்வம்) எப்படி உள்ளது? அமைதியா, கவலையா, அல்லது எளிதில் குலைகிறீர்களா?",
      te: 'మీ మానసిక స్థితి (సత్త్వ) ఎలా ఉంది? స్థిరంగా, ఆందోళన, లేక సులభంగా కలత చెందుతారా?',
      bn: "আপনার মানসিক অবস্থা ও মেজাজ (সত্ত্ব) কেমন? আপনি কি সাধারণত শান্ত, উদ্বিগ্ন, নাকি সহজে বিচলিত?",
      mr: "तुमची मानसिक स्थिती आणि स्वभाव (सत्त्व) कसा आहे? तुम्ही साधारण शांत, चिंताग्रस्त, की सहज विचलित होता का?",
    },
    quickReplies: {
      en: ['Very calm', 'Generally calm', 'Moderate', 'Anxious', 'Easily disturbed'],
      hi: ['बहुत शांत', 'आमतौर पर शांत', 'मध्यम', 'चिंतित', 'आसानी से विचलित'],
      ta: ['மிக அமைதி', 'பொதுவாக அமைதி', 'மிதமான', 'கவலை', 'எளிதில் குலைவு'],
      te: ['చాలా శాంత', 'సాధారణంగా శాంత', 'మధ్యమ', 'ఆందోళన', 'సులభంగా కలత'],
      bn: ['অত্যন্ত শান্ত', 'সাধারণত শান্ত', 'মধ্যম', 'উদ্বিগ্ন', 'সহজে বিচলিত'],
      mr: ['अतिशय शांत', 'साधारण शांत', 'मध्यम', 'चिंताग्रस्त', 'सहज विचलित'],
    },
  },
  {
    id: 'ahara_shakti', section: 'ayush.ahara_shakti',
    question: {
      en: "How is your digestive and food intake capacity (Ahara Shakti)? Do you digest food well and have good appetite?",
      hi: "आपकी पाचन और भोजन क्षमता (आहार शक्ति) कैसी है? क्या आप भोजन अच्छी तरह पचाते हैं और भूख अच्छी है?",
      ta: "உங்கள் செரிமம் மற்றும் உணவு உட்கொள்ளும் திறன் (ஆஹார சக்தி) எப்படி? நன்கு செரிக்கிறதா?",
      te: 'మీ జీర్ణ మరియు ఆహార సామర్థ్యం (ఆహార శక్తి) ఎలా ఉంది? బాగా జీర్ణమవుతుందా?',
      bn: "আপনার পাচন ও খাবার গ্রহণ ক্ষমতা (আহার শক্তি) কেমন? আপনি কি ভালো হজম করেন এবং ক্ষুধা ভালো?",
      mr: "तुमची पचन आणि खाद्य क्षमता (आहार शक्ती) कशी आहे? तुम्ही चांगले पचन करता आणि भूक चांगली आहे का?",
    },
    quickReplies: {
      en: ['Excellent appetite', 'Good digestion', 'Variable appetite', 'Poor appetite', 'Indigestion issues'],
      hi: ['उत्कृष्ट भूख', 'अच्छा पाचन', 'अनियमित भूख', 'कम भूख', 'अपचन की समस्या'],
      ta: ['சிறந்த பசி', 'நல்ல செரிமம்', 'மாறுபடும் பசி', 'குறைந்த பசி', 'செரிமான பிரச்சினை'],
      te: ['అద్భుత ఆకలి', 'మంచి జీర్ణం', 'మారుతూ ఉండే ఆకలి', 'తక్కువ ఆకలి', 'జీర్ణ సమస్యలు'],
      bn: ['চমৎকার ক্ষুধা', 'ভালো হজন', 'অনিয়মিত ক্ষুধা', 'কম ক্ষুধা', 'বদহজমের সমস্যা'],
      mr: ['उत्कृष्ट भूक', 'चांगले पचन', 'अनियमित भूक', 'कमी भूक', 'अपचनाची समस्या'],
    },
  },
  {
    id: 'vyayama_shakti', section: 'ayush.vyayama_shakti',
    question: {
      en: "What is your physical stamina and exercise capacity (Vyayama Shakti)? Can you do moderate physical exertion without fatigue?",
      hi: "आपकी शारीरिक सहनशक्ति (व्यायाम शक्ति) कैसी है? क्या आप बिना थके मध्यम व्यायाम कर सकते हैं?",
      ta: "உங்கள் உடற்திறன் (வியாயாம சக்தி) எப்படி? மிதமான உடற்பயிற்சி செய்ய முடியுமா?",
      te: 'మీ శారీరక సహనం (వ్యాయామ శక్తి) ఎలా ఉంది? మధ్యమ వ్యాయామం చేయగలరా?',
      bn: "আপনার শারীরিক সহনশীলতা (ব্যায়াম শক্তি) কেমন? আপনি কি মাঝারি ব্যায়াম করতে পারেন?",
      mr: "तुमची शारीरिक ताकद (व्यायाम शक्ती) कशी आहे? तुम्ही मध्यम व्यायाम करू शकता का?",
    },
    quickReplies: {
      en: ['Excellent stamina', 'Good capacity', 'Average', 'Low stamina', 'Easily fatigued'],
      hi: ['उत्कृष्ट सहनशक्ति', 'अच्छी क्षमता', 'औसत', 'कम सहनशक्ति', 'जल्दी थकता हूं'],
      ta: ['சிறந்த திறன்', 'நல்ல திறன்', 'சராசரி', 'குறைந்த திறன்', 'எளிதில் சோர்வு'],
      te: ['అద్భుత సహనం', 'మంచి సామర్థ్యం', 'సగటు', 'తక్కువ సహనం', 'సులభంగా అలసత్వం'],
      bn: ['চমৎকার সহনশীলতা', 'ভালো ক্ষমতা', 'গড়', 'কম সহনশীলতা', 'সহজে ক্লান্ত'],
      mr: ['उत्कृष्ट ताकद', 'चांगली क्षमता', 'सरासरी', 'कमी ताकद', 'लवकर थकतो'],
    },
  },
  {
    id: 'vaya', section: 'ayush.vaya',
    question: {
      en: "What is your age category (Vaya)? This helps us understand your life stage.",
      hi: "आपकी आयु श्रेणी (वय) क्या है? यह हमें आपके जीवन चरण को समझने में मदद करता है।",
      ta: "உங்கள் வயது வகை (வய) என்ன? இது உங்கள் வாழ்க்கை நிலையை புரிந்துகொள்ள உதவும்.",
      te: 'మీ వయసు వర్గం (వయ) ఏమిటి? ఇది మీ జీవిత దశను అర్థం చేసుకోవడానికి సహాయపడుతుంది.',
      bn: "আপনার বয়স শ্রেণী (বয়) কী? এটি আপনার জীবনের পর্যায় বুঝতে সাহায্য করে।",
      mr: "तुमची वयोगट (वय) काय आहे? हे तुमचा जीवनटप्पा समजण्यास मदत करते.",
    },
    quickReplies: {
      en: ['Child (0-12)', 'Youth (13-30)', 'Adult (31-60)', 'Elderly (60+)'],
      hi: ['बालक (0-12)', 'युवा (13-30)', 'वयस्क (31-60)', 'वृद्ध (60+)'],
      ta: ['குழந்தை (0-12)', 'இளைஞர் (13-30)', 'வயது (31-60)', 'முதியோர் (60+)'],
      te: ['బాలుడు (0-12)', 'యువకుడు (13-30)', 'వయోజనుడు (31-60)', 'వృద్ధుడు (60+)'],
      bn: ['শিশু (0-12)', 'তরুণ (13-30)', 'প্রাপ্তবয়স্ক (31-60)', 'প্রবীণ (60+)'],
      mr: ['बालक (0-12)', 'तरुण (13-30)', 'प्रौढ (31-60)', 'ज्येष्ठ (60+)'],
    },
  },
  {
    id: 'ahara_vihara', section: 'ayush.ahara_vihara',
    question: {
      en: "Describe your daily diet and lifestyle (Ahara-Vihara). Do you follow any specific dietary practices or daily routine?",
      hi: "अपने दैनिक आहार और जीवनशैली (आहार-विहार) का वर्णन करें। क्या आप कोई विशेष आहार या दिनचर्या अपनाते हैं?",
      ta: "உங்கள் தினசரி உணவு மற்றும் வாழ்க்கை முறையை (ஆஹார-விஹார) விவரிக்கவும்.",
      te: 'మీ రోజువారీ ఆహారం మరియు జీవనశైలి (ఆహార-విహార) గురించి చెప్పండి.',
      bn: "আপনার দৈনন্দিন খাদ্য ও জীবনযাত্রা (আহার-বিহার) বর্ণনা করুন।",
      mr: "तुमचे दैनंदिन आहार आणि जीवनशैली (आहार-विहार) वर्णन करा.",
    },
    quickReplies: {
      en: ['Vegetarian', 'Non-vegetarian', 'Vegan', 'Fasting regularly', 'Irregular meals', 'Regular routine'],
      hi: ['शाकाहारी', 'मांसाहारी', 'वीगन', 'नियमित उपवास', 'अनियमित भोजन', 'नियमित दिनचर्या'],
      ta: ['சைவம்', 'அசைவம்', 'வீகன்', 'வழக்கமான உபவாசம்', 'ஒழுங்கற்ற உணவு', 'ஒழுங்கான செயல்'],
      te: ['శాకాహారం', 'మాంసాహారం', 'వీగన్', 'రెగ్యులర్ ఉపవాసం', 'అక్రమ భోజనం', 'రెగ్యులర్ రొటీన్'],
      bn: ['নিরামিষ', 'আমিষ', 'ভেগান', 'নিয়মিত উপবাস', 'অনিয়মিত খাবার', 'নিয়মিত রুটিন'],
      mr: ['शाकाहारी', 'मांसाहारी', 'व्हीगन', 'नियमित उपवास', 'अनियमित जेवण', 'नियमित दिनचर्या'],
    },
  },
  {
    id: 'chief', section: 'chief_complaint',
    question: {
      en: "What brings you to the hospital today? What is your main health concern?",
      hi: "आज आप अस्पताल क्यों आए हैं? आपकी मुख्य स्वास्थ्य चिंता क्या है?",
      ta: "இன்று நீங்கள் மருத்துவமனைக்கு வந்த காரணம் என்ன? உங்கள் முக்கிய ஆரோக்கிய கவலை என்ன?",
      te: 'ఈరోజు మీరు ఆసుపత్రికి ఎందుకు వచ్చారు? మీ ప్రధాన ఆరోగ్య ఆందోళన ఏమిటి?',
      bn: "আজ আপনি হাসপাতালে কেন এসেছেন? আপনার প্রধান স্বাস্থ্য উদ্বেগ কী?",
      mr: "आज तुम्ही रुग्णालयात का आलात? तुमची मुख्य आरोग्याची काळजी काय आहे?",
    },
    quickReplies: {
      en: ['Digestive issues', 'Joint pain', 'Stress/Anxiety', 'Sleep problems', 'Skin issues', 'Other'],
      hi: ['पाचन समस्या', 'जोड़ों का दर्द', 'तनाव/चिंता', 'नींद की समस्या', 'त्वचा समस्या', 'अन्य'],
      ta: ['செரிமான பிரச்சினை', 'மூட்டு வலி', 'மன அழுத்தம்', 'தூக்க பிரச்சினை', 'தோல் பிரச்சினை', 'மற்றவை'],
      te: ['జీర్ణ సమస్యలు', 'కీళ్ల నొప్పి', 'ఒత్తిడి/ఆందోళన', 'నిద్ర సమస్యలు', 'చర్మ సమస్యలు', 'ఇతర'],
      bn: ['পাচন সমস্যা', 'জয়েন্ট ব্যথা', 'মানসিক চাপ', 'ঘুমের সমস্যা', 'ত্বকের সমস্যা', 'অন্যান্য'],
      mr: ['पचन समस्या', 'सांधेदुखी', 'तणाव/चिंता', 'झोपेची समस्या', 'त्वचेची समस्या', 'इतर'],
    },
  },
];

// Mock OCR extracted data
export const mockOcrResults = [
  {
    diagnosis: ['Type 2 Diabetes Mellitus', 'Hypertension'],
    medications: ['Metformin 500mg BD', 'Amlodipine 5mg OD', 'Atorvastatin 10mg HS'],
    labValues: [
      { name: 'HbA1c', value: '6.8', unit: '%', referenceRange: '<5.7', confidence: 0.95 },
      { name: 'Fasting Glucose', value: '126', unit: 'mg/dL', referenceRange: '70-100', confidence: 0.92 },
      { name: 'Total Cholesterol', value: '245', unit: 'mg/dL', referenceRange: '<200', confidence: 0.88 },
    ],
    patientName: 'Rajesh Kumar',
    date: '2024-03-10',
    hospital: 'City General Hospital',
  },
  {
    diagnosis: ['Hypothyroidism'],
    medications: ['Thyronorm 50mcg OD'],
    labValues: [
      { name: 'TSH', value: '8.5', unit: 'mIU/L', referenceRange: '0.4-4.0', confidence: 0.91 },
      { name: 'T3', value: '95', unit: 'ng/dL', referenceRange: '80-200', confidence: 0.85 },
      { name: 'T4', value: '6.2', unit: 'mcg/dL', referenceRange: '4.5-12', confidence: 0.87 },
    ],
    patientName: 'Rajesh Kumar',
    date: '2024-07-15',
    hospital: 'Thyrocare Labs',
  },
];

// TTS language code mapping
export const ttsLangCodes: Record<string, string> = {
  en: 'en-US',
  hi: 'hi-IN',
  ta: 'ta-IN',
  te: 'te-IN',
  bn: 'bn-IN',
  mr: 'mr-IN',
};

// Speech recognition language code mapping
export const sttLangCodes: Record<string, string> = {
  en: 'en-US',
  hi: 'hi-IN',
  ta: 'ta-IN',
  te: 'te-IN',
  bn: 'bn-IN',
  mr: 'mr-IN',
};

// Completion message for end of interview
export const completionMessages: Record<string, string> = {
  en: "Thank you! I have collected all the information. Let's move on to uploading any documents you may have, and then we'll review your summary together.",
  hi: "धन्यवाद! मैंने सभी जानकारी एकत्र कर ली है। आइए अब आपके दस्तावेज़ अपलोड करें, और फिर हम आपका सारांश देखेंगे।",
  ta: "நன்றி! அனைத்து தகவல்களையும் சேகரித்துள்ளேன். உங்கள் ஆவணங்களை பதிவேற்றலாம்.",
  te: 'ధన్యవాదాలు! అన్ని సమాచారం సేకరించాను. ఇప్పుడు మీ పత్రాలను అప్‌లోడ్ చేయండి.',
  bn: "ধন্যবাদ! আমি সব তথ্য সংগ্রহ করেছি। চলুন আপনার নথিপত্র আপলোড করি।",
  mr: "धन्यवाद! मी सर्व माहिती गोळा केली आहे. आता तुमची कागदपत्रे अपलोड करूया.",
};

// Red flag banner message
export const redFlagMessages: Record<string, string> = {
  en: "Urgent symptom detected. A triage nurse has been alerted. Please proceed to the triage desk if your symptoms worsen.",
  hi: "गंभीर लक्षण पाया गया है। ट्रायज नर्स को सूचित किया गया है। यदि लक्षण बिगड़ते हैं तो ट्रायज डेस्क पर जाएं।",
  ta: "அவசர அறிகுறி கண்டறியப்பட்டது. ட்ரையேஜ் நர்ஸ் அறிவிக்கப்பட்டார்.",
  te: 'అత్యవసర లక్షణం గుర్తించబడింది. ట్రయేజ్ నర్సుకు సూచించబడింది.',
  bn: "জরুরি লক্ষণ সনাক্ত হয়েছে। ট্রায়েজ নার্সকে জানানো হয়েছে।",
  mr: "तात्काळ लक्षण आढळले. ट्रायज नर्सला कळवण्यात आले आहे.",
};

// Translations for key UI strings
export const translations: Record<string, Record<string, string>> = {
  en: {
    startVisit: 'Start My Visit',
    welcome: 'Welcome to MediKiosk',
    tagline: 'AI-powered clinical history intake for better care',
    loginMobile: 'Login with Mobile OTP',
    loginAbha: 'Connect ABHA ID',
    walkIn: 'Continue as Walk-in Patient',
    consent: 'Consent & Privacy',
    consentDesc: 'Please review and agree to the following before we begin',
    chatbotDisclaimer: 'This assistant collects information for your doctor. It does not diagnose or treat.',
    ayushMode: 'AYUSH / Ayurveda Mode',
    uploadDocs: 'Upload Documents',
    reviewSummary: 'Review Your Summary',
    submitToDoctor: 'Submit to Doctor',
    aiAssistant: 'AI Clinical Assistant',
    question: 'Question',
    of: 'of',
    muteAudio: 'Mute audio',
    enableAudio: 'Enable audio',
    listening: 'Listening...',
    typeAnswer: 'Type your answer...',
    continueToUpload: 'Continue to Document Upload',
    backToHome: 'Back to Home',
    staffLogin: 'Staff Login',
    staffPortal: 'Staff Portal',
  },
  hi: {
    startVisit: 'अपनी विज़िट शुरू करें',
    welcome: 'मेडिकियोस्क में आपका स्वागत है',
    tagline: 'बेहतर देखभाल के लिए एआई-संचालित नैदानिक इतिहास',
    loginMobile: 'मोबाइल ओटीपी से लॉगिन करें',
    loginAbha: 'एभा आईडी कनेक्ट करें',
    walkIn: 'नए मरीज के रूप में जारी रखें',
    consent: 'सहमति और गोपनीयता',
    consentDesc: 'शुरू करने से पहले कृपया निम्नलिखित की समीक्षा करें',
    chatbotDisclaimer: 'यह सहायक आपके डॉक्टर के लिए जानकारी एकत्र करता है। यह निदान या उपचार नहीं करता।',
    ayushMode: 'आयुष / आयुर्वेद मोड',
    uploadDocs: 'दस्तावेज़ अपलोड करें',
    reviewSummary: 'अपना सारांश देखें',
    submitToDoctor: 'डॉक्टर को भेजें',
    aiAssistant: 'एआई नैदानिक सहायक',
    question: 'प्रश्न',
    of: 'में से',
    muteAudio: 'ऑडियो बंद करें',
    enableAudio: 'ऑडियो चालू करें',
    listening: 'सुन रहा हूं...',
    typeAnswer: 'अपना उत्तर लिखें...',
    continueToUpload: 'दस्तावेज़ अपलोड पर जाएं',
    backToHome: 'होम पर वापस',
    staffLogin: 'स्टाफ लॉगिन',
    staffPortal: 'स्टाफ पोर्टल',
  },
  ta: {
    startVisit: 'உங்கள் வருகையைத் தொடங்குங்கள்',
    welcome: 'மெடிகியோஸ்க்கிற்கு வரவேற்கிறோம்',
    tagline: 'சிறந்த கவனிப்புக்கான AI மருத்துவ வரலாற்று சேகரிப்பு',
    loginMobile: 'மொபைல் OTP உள்நுழைவு',
    loginAbha: 'ABHA ID இணைக்கவும்',
    walkIn: 'புதிய நோயாளியாக தொடரவும்',
    consent: 'ஒப்புதல் & தனியுரிமை',
    consentDesc: 'தொடங்குவதற்கு முன் பின்வருவனவற்றை மதிப்பாய்வு செய்யவும்',
    chatbotDisclaimer: 'இந்த உதவியாளர் உங்கள் மருத்துவருக்காக தகவல் சேகரிக்கிறார்.',
    ayushMode: 'ஆயுஷ் / ஆயுர்வேத முறை',
    uploadDocs: 'ஆவணங்களை பதிவேற்றவும்',
    reviewSummary: 'உங்கள் சுருக்கத்தை மதிப்பாய்வு செய்யவும்',
    submitToDoctor: 'மருத்துவருக்கு அனுப்பு',
    aiAssistant: 'AI மருத்துவ உதவியாளர்',
    question: 'கேள்வி',
    of: 'இல்',
    muteAudio: 'ஆடியோ அணைக்க',
    enableAudio: 'ஆடியோ இயக்க',
    listening: 'கேட்கிறேன்...',
    typeAnswer: 'உங்கள் பதிலை தட்டச்சு செய்யவும்...',
    continueToUpload: 'ஆவண பதிவேற்றத்திற்கு தொடரவும்',
    backToHome: 'முகப்பிற்கு திரும்ப',
    staffLogin: 'ஊழியர் உள்நுழைவு',
    staffPortal: 'ஊழியர் போர்டல்',
  },
  te: {
    startVisit: 'మీ విజిట్‌ను ప్రారంభించండి',
    welcome: 'మెడికియోస్క్‌కు స్వాగతం',
    tagline: 'మెరుగైన సంరక్షణ కోసం AI క్లినికల్ చరిత్ర',
    loginMobile: 'మొబైల్ OTP లాగిన్',
    loginAbha: 'ABHA ID కనెక్ట్ చేయండి',
    walkIn: 'కొత్త రోగిగా కొనసాగండి',
    consent: 'అంగీకారం & గోప్యత',
    consentDesc: 'ప్రారంభించే ముందు కింది వాటిని సమీక్షించండి',
    chatbotDisclaimer: 'ఈ సహాయకుడు మీ డాక్టర్ కోసం సమాచారం సేకరిస్తారు.',
    ayushMode: 'ఆయుష్ / ఆయుర్వేద మోడ్',
    uploadDocs: 'పత్రాలను అప్‌లోడ్ చేయండి',
    reviewSummary: 'మీ సారాంశాన్ని సమీక్షించండి',
    submitToDoctor: 'డాక్టర్‌కు పంపండి',
    aiAssistant: 'AI క్లినికల్ సహాయకుడు',
    question: 'ప్రశ్న',
    of: 'లో',
    muteAudio: 'ఆడియో ఆపు',
    enableAudio: 'ఆడియో ఆన్ చేయి',
    listening: 'వింది...',
    typeAnswer: 'మీ సమాధానం టైప్ చేయండి...',
    continueToUpload: 'పత్రాల అప్‌లోడ్‌కు కొనసాగండి',
    backToHome: 'హోమ్‌కు తిరిగి వెళ్ళు',
    staffLogin: 'స్టాఫ్ లాగిన్',
    staffPortal: 'స్టాఫ్ పోర్టల్',
  },
  bn: {
    startVisit: 'আপনার ভিজিট শুরু করুন',
    welcome: 'মেডিকিয়োস্কে স্বাগতম',
    tagline: 'উন্নত পরিচর্যার জন্য AI-চালিত ক্লিনিকাল ইতিহাস',
    loginMobile: 'মোবাইল OTP লগইন',
    loginAbha: 'ABHA ID সংযুক্ত করুন',
    walkIn: 'নতুন রোগী হিসেবে এগিয়ে যান',
    consent: 'সম্মতি ও গোপনীয়তা',
    consentDesc: 'শুরু করার আগে নিম্নলিখিত পর্যালোচনা করুন',
    chatbotDisclaimer: 'এই সহকারী আপনার ডাক্তারের জন্য তথ্য সংগ্রহ করেন।',
    ayushMode: 'আয়ুষ / আয়ুর্বেদ মোড',
    uploadDocs: 'নথিপত্র আপলোড করুন',
    reviewSummary: 'আপনার সারসংক্ষেপ পর্যালোচনা করুন',
    submitToDoctor: 'ডাক্তারের কাছে পাঠান',
    aiAssistant: 'AI ক্লিনিকাল সহকারী',
    question: 'প্রশ্ন',
    of: 'এর মধ্যে',
    muteAudio: 'অডিও বন্ধ করুন',
    enableAudio: 'অডিও চালু করুন',
    listening: 'শুনছি...',
    typeAnswer: 'আপনার উত্তর লিখুন...',
    continueToUpload: 'নথিপত্র আপলোডে এগিয়ে যান',
    backToHome: 'হোমে ফিরে যান',
    staffLogin: 'স্টাফ লগইন',
    staffPortal: 'স্টাফ পোর্টাল',
  },
  mr: {
    startVisit: 'तुमची भेट सुरू करा',
    welcome: 'मेडिकियोस्कमध्ये आपले स्वागत आहे',
    tagline: 'उत्तम काळजीसाठी AI-चालित क्लिनिकल इतिहास',
    loginMobile: 'मोबाईल OTP लॉगिन',
    loginAbha: 'ABHA ID कनेक्ट करा',
    walkIn: 'नवीन रुग्ण म्हणून पुढे जा',
    consent: 'संमती आणि गोपनीयता',
    consentDesc: 'सुरू करण्यापूर्वी खालील वाचा',
    chatbotDisclaimer: 'हा सहाय्यक तुमच्या डॉक्टरांसाठी माहिती गोळा करतो.',
    ayushMode: 'आयुष / आयुर्वेद मोड',
    uploadDocs: 'कागदपत्रे अपलोड करा',
    reviewSummary: 'तुमचा सारांश पाहा',
    submitToDoctor: 'डॉक्टरांना पाठवा',
    aiAssistant: 'AI क्लिनिकल सहाय्यक',
    question: 'प्रश्न',
    of: 'पैकी',
    muteAudio: 'ऑडिओ बंद करा',
    enableAudio: 'ऑडिओ चालू करा',
    listening: 'ऐकत आहे...',
    typeAnswer: 'तुमचे उत्तर लिहा...',
    continueToUpload: 'कागदपत्र अपलोडवर जा',
    backToHome: 'होमवर परत जा',
    staffLogin: 'स्टाफ लॉगिन',
    staffPortal: 'स्टाफ पोर्टल',
  },
};
